language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - sys-img-armeabi-v7a-android-27

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-26"